### PR TITLE
Fix PyTorch 2.7.1 positional argument requirement for checkpoint APIs

### LINKED ISSUE #996: [Bug]:  Checkpoint save crashes with TypeError (affects all instance types) on 3.test_cases/pytorch/FSDP
### Prerequisites

- [x] I have searched existing issues to make sure this bug has not already been reported.
- [x] I have verified the issue against the latest `main` branch.

## Environment
- Instance type: ml.g5.12xlarge (4x NVIDIA A10G GPUs per node)
- Cluster: SageMaker HyperPod with Slurm orchestration, 2 nodes
- PyTorch version: 2.7.1+cu128 (as pinned in `src/requirements.txt`)
- Transformers: 4.53.0 (as pinned in `src/requirements.txt`)
- Model: Llama 3.2 1B (`llama3_2_1b-training.sbatch`)

### Bug Description

**File:** `src/model_utils/checkpoint.py`, line 33

**Error:**
```
TypeError: get_optimizer_state_dict() got an unexpected keyword argument 'optimizer'
```

**Cause:** The `save_checkpoint` function calls `get_optimizer_state_dict(model=model, optimizer=optimizer)` using keyword arguments. In PyTorch 2.7.1, `torch.distributed.checkpoint.state_dict.get_optimizer_state_dict` changed its signature to require positional arguments.

**Impact:** Training crashes at the first checkpoint save (step 50 by default). This affects all instance types since `requirements.txt` pins `torch==2.7.1`.

**Fix:**
```python
# Before (broken with PyTorch 2.7.1)
optimizer_state_dict = get_optimizer_state_dict(
    model=model,
    optimizer=optimizer,
)

# After (works with PyTorch 2.7.1)
optimizer_state_dict = get_optimizer_state_dict(model, optimizer)
```

Same change needed for `set_optimizer_state_dict` and `set_model_state_dict` in the `load_checkpoint` function.

### Steps to Reproduce

Run 3.test_cases/pytorch/FSDP

### Relevant Log Output

```shell

```

### PR DESCRIPTION
**Pull request by jothikaaravindhan**
## Purpose

Fixes the PyTorch 2.7.1 API change that breaks checkpoint save/load in FSDP training.  

## Related Issues

Closes #996 

## Changes

- Updated `checkpoint.py` to use **positional arguments**:

```python
optimizer_state_dict = get_optimizer_state_dict(model, optimizer)
set_model_state_dict(model, state_dict["model"])
set_optimizer_state_dict(model, optimizer, state_dict["optim"])
```

## Testing

- A minimal local test file `validate_checkpoint_api_test.py` was created that initializes a small FSDP model and optimizer, calls the checkpoint APIs, and confirms that all `get/set` state dict operations succeed. The test fails before the fix (TypeError) and passes after applying positional arguments, validating the change.

```shell
> python3 validate_checkpoint_api_test.py 
Initializing distributed...
Testing get_model_state_dict...
Testing get_optimizer_state_dict...
Testing set_model_state_dict...
Testing set_optimizer_state_dict...
All checkpoint API calls succeeded.
```

### CODE REVIEW

**Comment by KeitaW** [comment]
Thank you @jothikaaravindhan ! Could you please paste the validation script here so that reviewers can reproduce what you have tested?

**Comment by jothikaaravindhan** [comment]
This is validation used to reproduce the issue in my local and test the fix.

```python
import torch
import torch.nn as nn
import torch.optim as optim
import torch.distributed as dist

from torch.distributed.checkpoint.state_dict import (
  get_model_state_dict,
  get_optimizer_state_dict,
  set_model_state_dict,
  set_optimizer_state_dict,
)

def init_dist():
  if not dist.is_initialized():
    dist.init_process_group(
      backend="gloo",
      init_method="tcp://127.0.0.1:29500",
      rank=0,
      world_size=1,
    )

def test_checkpoint_api():
  print("Initializing distributed...")
  init_dist()

  model = nn.Linear(10, 2)
  optimizer = optim.Adam(model.parameters(), lr=0.001)

  print("Testing get_model_state_dict...")
  # model_sd = get_model_state_dict(model=model)
  model_sd = get_model_state_dict(model)

  print("Testing get_optimizer_state_dict...")
  # optim_sd = get_optimizer_state_dict(model=model, optimizer=optimizer)
  optim_sd = get_optimizer_state_dict(model, optimizer)


  print("Testing set_model_state_dict...")
  # set_model_state_dict(model=model, model_state_dict=model_sd)
  set_model_state_dict(model, model_sd)

  print("Testing set_optimizer_state_dict...")
  # set_optimizer_state_dict(model=model, optimizer=optimizer, optim_state_dict=optim_sd)
  set_optimizer_state_dict(model, optimizer, optim_sd)

  print("All checkpoint API calls succeeded.")

  dist.destroy_process_group()


if __name__ == "__main__":
  test_checkpoint_api()
```

**Comment by KeitaW** [comment]
Hi @aravneelaws  could you please take a look?

**Comment by aravneelaws** [comment]
Will review this today and merge it if no issue! :)

**Comment by aravneelaws** [comment]
Reviewed this and it looks good. I faced similar ckpt crashing on the llama3.2 1b example. This will fix the problem. Merging this now. Thanks, @jothikaaravindhan
